### ISSUE TITLE
yaspe fails to complete if pButtons contains routine names including the word "Freeze"

### ISSUE THREAD

**Issue by silvermoona** [murrayo/yaspe#1]
Hi

thank you for providing such a great tool!

I noticed one small issue. If a routine name contains the word "Freeze" and is listed in CSTAT -R, e.g.

      32132  4096   0   4     1   0  D  331ce6e8  6179438f   116 379956d5  HistRackPlacement.CHFreezer.0 

yaspe fails to complete the job with the error

Traceback (most recent call last):
  File "/app/./yaspe.py", line 1018, in <module>
Create and Chart
    mainline(
  File "/app/./yaspe.py", line 826, in mainline
    sp_dict = sp_check.system_check(input_file)
  File "/app/sp_check.py", line 103, in system_check
    sp_dict["freeze"] = (line.split("=")[1]).strip()
IndexError: list index out of range

If I remove the line with the routine containing the word "Freeze" everything works fine!

Tested on version 0.2.14 (Intel)

**Comment by murrayo** [comment]
D'oh, 

Thanks for bringing this to my attention... 

I will fix it today.

**Comment by murrayo** [comment]
Hi, I have fixed the problem. In the lates version (yaspe.py -v)
0.2.16

**Comment by murrayo** [comment]
closed
